export const products = [
  {
    id: "1",
    name: "Barbour Barlow Flatcap",
    description: "The Barlow Flat Cap is a classic cap from Barbour.",
    price: 44.9,
    image: "img/men/menhat.png",
    category: "men",
  },
  {
    id: "2",
    name: "7V Battery Heated Jacket",
    description: "Additional heat to keep your core warm and toasty during all kinds of cold weather conditions, such as winter sports, outdoor camping, and others.",
    price: 76.95,
    image: "img/men/menjacket.jpg",
    category: "men",
  },
  {
    id: "3",
    name: "Satu Adventure Pants",
    description: "Satu - named after the Malaysian word for 'one,' these pants are designed to do it all. Whether you're backpacking or heading to the office, the Satu Adventure Pants offer versatility, style, and performance.",
    price: 89.99,
    image: "img/men/menpants.png",
    category: "men",
  },
  {
    id: "4",
    name: "General Construction Work Gloves",
    description: "Featuring an open back for ventilation and an ergonomic design that reduces hand fatigue, these gloves provide a high level comfort and functionality in a variety of conditions.",
    price: 19.99,
    image: "img/men/mengloves.jpg",
    category: "men",
  },
  {
    id: "5",
    name: "ELTEN Sicherheitsstiefel STEFANO XXSG",
    description: "With a cowhide leather upper, this safety boot is particularly robust and ideal for construction sites. The breathable textile lining ensures a comfortable foot climate.",
    price: 148.9,
    image: "img/men/menshoes.png",
    category: "men",
  },
  {
    id: "6",
    name: "Uposao Fur Hat",
    description: "New fashion design, one size fit most, elastic, soft and fashionable, very comfortable stretch fabric.",
    price: 20.9,
    image: "img/women/womenhat.jpg",
    category: "women",
  },
  {
    id: "7",
    name: "iheat Heated Jacket",
    description: "4 carbon fiber heating elements generate heat across core body areas (left & right chest, mid-back,neck).",
    price: 100.95,
    image: "img/women/womenjacket.jpg",
    category: "women",
  },
  {
    id: "8",
    name: "CRZ YOGA Cross Waist Leggings",
    description: "Butterluxe collection uses high-end fabric, engineered for luxurious comfort and made for all ways you move.",
    price: 35.99,
    image: "img/women/womenleggs.jpg",
    category: "women",
  },
  {
    id: "9",
    name: "Battery Powered Heated Socks",
    description: "Electric socks adopt the new generation of carbon fiber 3D heating technology can be heated quickly and fast heating in 10 seconds.",
    price: 50.65,
    image: "img/women/womensocks.jpg",
    category: "women",
  },
  {
    id: "10",
    name: "Even&Odd Platform Boots",
    description: "The wide, rounded toe shape and grooved, air-cushioned sole keep you bouncing even on your longest days.",
    price: 48.9,
    image: "img/women/womenboots.png",
    category: "women",
  },
];
