export const products = [
  {
    id: "1",
    name: "Small (S) – Intimate & Charming.<br> A delicate oil painting on canvas that captures emotion in every brushstroke. Perfect for gifts, cozy spaces, or keeping a special memory close. Small in size, big in heart.<br> Size: 20 x 30 cm",
    description: "A delicate oil painting on canvas that captures emotion in every brushstroke. Perfect for gifts, cozy spaces, or keeping a special memory close. Small in size, big in heart.",
    price: 44.9,
    image: "img/portraits/Small.jpg",
    category: "portraits",
  },
  {
    id: "2",
    name: "Medium (M) – Bold & Personal.<br> This medium-sized oil portrait brings your personality to life with rich color and detail. Ideal for home décor or meaningful gifts that make a lasting impression.<br> Size: 40 x 50 cm.",
    description: "This medium-sized oil portrait brings your personality to life with rich color and detail. Ideal for home décor or meaningful gifts that make a lasting impression.",
    price: 76.95,
    image: "img/portraits/Medium.jpg",
    category: "portraits",
  },
  {
    id: "3",
    name: "Large (L) – Striking & Timeless.<br> A statement piece in oil on canvas—grand, expressive, and unforgettable. This large portrait is perfect for making an impact and celebrating your unique story in full scale.<br> Size: 60 x 70 cm.",
    description: "A statement piece in oil on canvas—grand, expressive, and unforgettable. This large portrait is perfect for making an impact and celebrating your unique story in full scale.",
    price: 89.99,
    image: "img/portraits/Large.jpg",
    category: "portraits",
  },
  {
    id: "4",
    name: "Blazers",
    description: "New fashion design, one size fit most, elastic, soft and fashionable, very comfortable stretch fabric.",
    price: 20.9,
    image: "img/textiles/blazer.jpg",
    category: "textiles",
  },
  {
    id: "5",
    name: "Jackets",
    description: "4 carbon fiber heating elements generate heat across core body areas (left & right chest, mid-back,neck).",
    price: 100.95,
    image: "img/textiles/jacket.jpg",
    category: "textiles",
  },
  {
    id: "6",
    name: "Pockets",
    description: "Butterluxe collection uses high-end fabric, engineered for luxurious comfort and made for all ways you move.",
    price: 35.99,
    image: "img/textiles/pockets.jpg",
    category: "textiles",
  },
];
